[build]
command = "rm -rf .next node_modules/.cache && pnpm run build && pnpm run db:migrate && pnpm run db:seed-public-user"
publish = ".next"

[build.environment]
NODE_OPTIONS = "--max-old-space-size=4096"

[[plugins]]
package = "@netlify/plugin-nextjs"

[template.environment]
OPENAI_API_KEY = "set your OpenAI API Key"
